require('dotenv').config();
const mongoose = require('mongoose');

const castData = [
  {tmdbId:1479832,cast:[{name:"Wamiqa Gabbi",character:"Chandra",photo:"/e1CNXkH2scGeoabOTowFJJxX2YF.jpg"},{name:"Sanjana Krishnamoorthy",character:"Parvathi",photo:"/eNYxaRfb8xyj0OoNa46txZhzuWw.jpg"},{name:"Avinash Raghudevan",character:"Kitty",photo:"/AuiRkWkzpmZU2P88s1wwcqVDKJV.jpg"},{name:"Jawahar Sakthi",character:"Karuppan",photo:"/tujqtpUT92SDeo2AuUJiJGKBfYp.jpg"},{name:"Sharath Ravi",character:"Chunnilal",photo:"/5hgdkBe06e6xRRTPvQEPcoanC2u.jpg"},{name:"Thalaivasal Vijay",character:"Arasu",photo:"/2mlbBSwHF2nzlPpVnjXpTKLaoxQ.jpg"}]},
  {tmdbId:1122030,cast:[{name:"Alia Bhatt",character:"Sita",photo:"/suudEC5cdE3g5kB1BjCPfvfeQZY.jpg"},{name:"Sharvari",character:"Durga",photo:"/zAkx24qd7eH1Ck3ouBnPOysAOaJ.jpg"},{name:"Bobby Deol",character:"Fateh Singh Lakhawat",photo:"/2npVa3PduichY8e7qBiE54m9VVP.jpg"},{name:"Anil Kapoor",character:"Vikrant Kaul",photo:"/dwvnpiwg9m2zj0VHzlgzEotFl0G.jpg"},{name:"Dibyendu Bhattacharya",character:"Dr. John Verghese",photo:"/uLlGKCL9y5CFBwcAafTDQhupz5h.jpg"},{name:"Dia Mirza",character:"Janaki Kaul",photo:"/oJSZlMkIGC1Yr8QxdBLliUjPRSd.jpg"},{name:"Hrithik Roshan",character:"Kabir Dhaliwal",photo:"/5O7WrWe84WDFj7td64NVsobtHf3.jpg"}]},
  {tmdbId:1303331,cast:[{name:"Ajay Devgn",character:"Guddu",photo:"/vnHQQFzTjJ0sv14DGMIoKa3qTxN.jpg"},{name:"Arshad Warsi",character:"Adi",photo:"/iXSA1C7B5mtoUrfDZ2sULE28bww.jpg"},{name:"Riteish Deshmukh",character:"Lallan",photo:"/b4Mwk9dDgMS82269iBX7V1YsOpu.jpg"},{name:"Javed Jaffrey",character:"Manav",photo:"/5JvPPxLsDEUFy6qDVawM3Itl6NV.jpg"},{name:"Sanjay Mishra",character:"Johnny",photo:"/4MGKohKGU4v9SoXcQKCcC4e4Bpi.jpg"},{name:"Ravi Kishan",character:"Adhoora",photo:"/rkUTRk0tuA98RepP9jhgcCbhHqy.jpg"},{name:"Upendra Limaye",character:"Prithvi",photo:"/vFELR5TiBfc6LkLvI5kC5lpEnHv.jpg"},{name:"Anjali Anand",character:"Paro",photo:"/x35BaUKgC5kHYQtMxazfL07gGoO.jpg"}]},
  {tmdbId:1432631,cast:[{name:"Atharvaa Murali",character:"Idhayam Murali",photo:"/fRo2OQFMxGNl1gqPJHnwFSi8XT5.jpg"},{name:"Fahadh Faasil",character:"Suriya",photo:"/wmkwZWFHqMptqdt4HacMIAe8OBP.jpg"},{name:"Preity Mukhundhan",character:"Samyuktha / Samantha",photo:"/3Rx9ci7YYwrSraXWMaBDW3iB4es.jpg"},{name:"Kayadu Lohar",character:"Amudha",photo:"/pHaMPnrfnWvTPZA4IOmZk8BHY0U.jpg"},{name:"Niharika NM",character:"Lara Dominic",photo:"/u9fD9XNUSiw1b9pQoTYUyl9pWj4.jpg"},{name:"Malavika Mohanan",character:"Aditi",photo:"/ukA3kk56Eqhn8g42an73CgdpXC5.jpg"}]},
  {tmdbId:1108427,cast:[{name:"Catherine Laga'aia",character:"Moana",photo:"/2KRIRDwy1CtY7Bge3aqVZrORelc.jpg"},{name:"Dwayne Johnson",character:"Maui",photo:"/5QApZVV8FUFlVxQpIK3Ew6cqotq.jpg"},{name:"Rena Owen",character:"Gramma Tala",photo:"/648ZdDBmlx6OFDFRmgAbh6q5LBo.jpg"},{name:"John Tui",character:"Chief Tui",photo:"/2jIc9M5kl2GmK8fZtbtUr2s1jkS.jpg"},{name:"Frankie Adams",character:"Sina",photo:"/aAUHUSf0lh3OBRoaiCRL9ep8lfL.jpg"},{name:"Jemaine Clement",character:"Tamatoa",photo:"/6eiNbeurpHb2fxIeT0RrJ0wRI25.jpg"}]},
  {tmdbId:1442396,cast:[{name:"Virat Karrna",character:"Rudhra",photo:null},{name:"Nabha Natesh",character:"Parvathi",photo:"/4XK99gs2ytNft59xgsw2WPGcPkF.jpg"},{name:"Daksha Nagarkar",character:"Priyamani",photo:"/vnYsR2Vynqx21pMwRBCxm0CsUmh.jpg"},{name:"Anasuya Bharadwaj",character:"Leelavathi",photo:"/adfyR0yHuTdj3sMiJQNDtBBXz9Q.jpg"},{name:"Mahesh Manjrekar",character:"Suvarna",photo:"/4lFytre6m4SruIUpUIoyNjsMo7F.jpg"},{name:"Jagapati Babu",character:"Prabhakar",photo:"/bm72k6FmDxhxtZsl1xvxoz88Hkm.jpg"}]},
  {tmdbId:1212763,cast:[{name:"Souheila Yacoub",character:"Alice",photo:"/A233BHgXw0dzbeOpvHfJwL9gLy1.jpg"},{name:"Tandi Wright",character:"Susan",photo:"/zluVB3mzZVlv8D013OgeQLhzNEw.jpg"},{name:"Hunter Doohan",character:"Joseph",photo:"/ihno5ut6ha8TaubQFgl5Ozco2K1.jpg"},{name:"Luciane Buchanan",character:"Thya",photo:"/9fTzSU4310StDoO9T0nQyGOLurn.jpg"},{name:"Erroll Shand",character:"Edgar",photo:"/75nc5lUcp1So9RTNNr08NZ0oQDG.jpg"},{name:"Maude Davey",character:"Polly",photo:"/gJsnWVfgcyFrTYPVvcJrvIjIH1k.jpg"}]},
  {tmdbId:1739294,cast:[{name:"Yash Soni",character:"Ratan",photo:"/uBasvWxd4YEXZNniZsdIzEUVBDt.jpg"},{name:"Deeksha Joshi",character:"Birwa",photo:"/2w5q4vb6IPtd03qNJjAVKqYfFex.jpg"},{name:"Shruhad Goswami",character:"Babu",photo:null},{name:"Tarjani Bhadla",character:"Purva",photo:null},{name:"Prachi Thaker",character:"Urmi",photo:null}]},
  {tmdbId:1509599,cast:[{name:"Vishnu Vishal",character:"Veera",photo:"/3i9sG0v3sQ8sQCcVgiGI3HezH8r.jpg"},{name:"Aishwarya Lekshmi",character:"Keerthi",photo:"/b3yxjhc62X0JZghaRTYNMVrI78a.jpg"},{name:"Karunas",character:"'Mama' Ratnam",photo:"/dnh00MeOyiWFQ21l5az3UVJ5rhp.jpg"},{name:"Munishkanth",character:"'Chithappa' Ganesan",photo:"/n2SjFPNv3EN1ziqfdpyjiEvoqt7.jpg"},{name:"Kaali Venkat",character:"'Sattam' Sattanathan",photo:"/w36lwArVQb0lDIJEenBECHqSdpG.jpg"},{name:"Lizzie Antony",character:"Ratnam's Wife",photo:"/ixHVL81eCUTr1iy3C8d1EwScukK.jpg"}]},
  {tmdbId:1408170,cast:[{name:"Akhil Akkineni",character:"Lenin",photo:"/e8vXTFBfPsQoMTJ4EwjHaz1CIoh.jpg"},{name:"Bhagyashri Borse",character:"Bharathi",photo:"/z1q1PEKFHVdKrBzD1Wk2q2WQMrj.jpg"},{name:"Sivaji Sontineni",character:"Yatirajulu",photo:"/rYttVZsngTbaS2ElxDiIiQ32RbL.jpg"},{name:"Easwari Rao",character:"Jayanthi",photo:"/fjyvQ45YZcovy2Egj2eux8UiuHU.jpg"},{name:"Brahmaji",character:"Damodaram",photo:"/xDTE7POq1bkyjLINxdy7rW4wQlg.jpg"},{name:"N.T. Rama Rao Jr.",character:"Narrator",photo:"/5ycQgZ3SPUa12bq0yn1jpToBq9X.jpg"}]},
  {tmdbId:1368337,cast:[{name:"Matt Damon",character:"Odysseus",photo:"/aCvBXTAR9B1qRjIRzMBYhhbm1fR.jpg"},{name:"Tom Holland",character:"Telemachus",photo:"/xKBAaPIa1c7tzZD3Y0MhBLv4hPE.jpg"},{name:"Anne Hathaway",character:"Penelope",photo:"/nbccV2pMoyLTCeg5DQip24Eq0Jp.jpg"},{name:"Robert Pattinson",character:"Antinous",photo:"/3qZ09UE7lN6AtorfXFRYpEtSY93.jpg"},{name:"Himesh Patel",character:"Eurylochus",photo:"/4mfOQgnwmewNURfQApyyHxt1qUF.jpg"},{name:"Charlize Theron",character:"Calypso",photo:"/9coVbqj35Fa5dWxlX5K9pDCqKfa.jpg"},{name:"John Leguizamo",character:"Eumaeus",photo:"/kwYCdxTlDh9zauUCg4mp2XTCQTw.jpg"},{name:"Travis Scott",character:"Bard",photo:"/eBdm7HQS6lLGg4BocgfoJ5qB9yp.jpg"}]},
  {tmdbId:1489543,cast:[{name:"R. Madhavan",character:"GD Naidu",photo:"/gaDrAdXxIrbBRCd9cX8YvJDEuLb.jpg"},{name:"Priyamani",character:"Chellammal",photo:"/i1sZtQcphZWJij3LoR9M6QY9i4z.jpg"},{name:"Sathyaraj",character:"Ramaiah Pillai",photo:"/lnlBZ7V3K3Z3OIsjCd0zkKx26L3.jpg"},{name:"Jayaram",character:"Ambalapara Krishnan",photo:"/cc1SfVFctuYH353NgxXNBoAFX2d.jpg"},{name:"Dushara Vijayan",character:"Ranganayaki",photo:"/5C5V9qdYil7LVCp8LqctZCEsu1n.jpg"},{name:"Thambi Ramaiah",character:"Ramasamy Mama",photo:"/murNGZdySdA7uKgLBeMwOK4wEdg.jpg"}]},
  {tmdbId:969681,cast:[{name:"Tom Holland",character:"Peter Parker / Spider-Man",photo:"/xKBAaPIa1c7tzZD3Y0MhBLv4hPE.jpg"},{name:"Sadie Sink",character:"Jean Grey",photo:"/92FddzBfK50XOUbtwjqHPraoGHy.jpg"},{name:"Zendaya",character:"MJ",photo:"/3WdOloHpjtjL96uVOhFRRCcYSwq.jpg"},{name:"Jon Bernthal",character:"Frank Castle / Punisher",photo:"/o0t6EVkJOrFAjESDilZUlf46IbQ.jpg"},{name:"Jacob Batalon",character:"Ned Leeds",photo:"/53YhaL4xw4Sb1ssoHkeSSBaO29c.jpg"},{name:"Mark Ruffalo",character:"Bruce Banner / Hulk",photo:"/5GilHMOt5PAQh6rlUKZzGmaKEI7.jpg"},{name:"Tramell Tillman",character:"William Metzger",photo:"/bEA15zMnkcXlRroYjKrFUWiiK7y.jpg"},{name:"Liza Colon-Zayas",character:"Detective Jean DeWolff",photo:"/qBb5eYEoZAlStrRXvsFlKukKJG8.jpg"}]},
  {tmdbId:1235877,cast:[{name:"Vijay",character:"Thalapathy Vetri Kondan",photo:"/zbQ1sDRVRHkroWwvrnqYKMerl66.jpg"},{name:"Pooja Hegde",character:"Kayal",photo:"/t09lf8vem5MRk3KaALcdgehreXg.jpg"},{name:"Bobby Deol",character:"John Himler",photo:"/2npVa3PduichY8e7qBiE54m9VVP.jpg"},{name:"Mamitha Baiju",character:"Vijayalakshmi",photo:"/tGEFW7uGdYrvZ2f3FP8JH5Yh5L2.jpg"},{name:"Priyamani",character:"Sheela Rani",photo:"/i1sZtQcphZWJij3LoR9M6QY9i4z.jpg"},{name:"Prakash Raj",character:"Roja Rangasamy",photo:"/dJvFZOXmZdkYCOUcKTXQAhBcAoH.jpg"}]},
  {tmdbId:1545486,cast:[{name:"Kunchacko Boban",character:"CPO Shelly K",photo:"/1jdbIaYOBuhPNGS8XCqlzMsb0SV.jpg"},{name:"Lijomol Jose",character:"",photo:"/vXFBgF6NMON7L4RzZ6B35lOVYOu.jpg"},{name:"Gokulan",character:"",photo:"/y36ZVFg40z8XKo7nhpZkC6N0S4N.jpg"},{name:"Siddique",character:"",photo:"/tMv7QsmYlXAXtP75D3eIxXHpgTv.jpg"},{name:"Kottayam Nazeer",character:"",photo:"/vN0cHxgDIE5DKUeL2F0nmIhTIoZ.jpg"}]},
  {tmdbId:1315772,cast:[{name:"Allison Janney",character:"Olivia (voice)",photo:"/kSaSnQ9xU8eVNL0mTppab95dZA8.jpg"},{name:"Christoph Waltz",character:"Max (voice)",photo:"/jMvLGCVXLaBqjRLf5olyvEucZob.jpg"},{name:"Jeff Bridges",character:"Frank / Elwood (voice)",photo:"/xms1RAY6q7Lzp7wNeRCB0kzhucn.jpg"},{name:"Jesse Eisenberg",character:"Dort (voice)",photo:"/yYhwWRcxDHTn63gSEF1vnDAD7cD.jpg"},{name:"Zoey Deutch",character:"Debbie (voice)",photo:"/tn6ErnytTct7HNAFG2dW17QcBk5.jpg"},{name:"Bobby Moynihan",character:"Phillips (voice)",photo:"/gOvwNz5joi5yWJ7dAhuF8WA2aas.jpg"}]},
  {tmdbId:1739212,cast:[{name:"Deepak Tijori",character:"",photo:"/3Vnt2RxkMYrPDuFMhdU2WWeVZqT.jpg"},{name:"Bhavya Gandhi",character:"",photo:"/aaLty8tAYmIjUlrQLMwdCJtaWnn.jpg"},{name:"Raunaq Kamdar",character:"",photo:"/yT6okFO4nWT1HXLtJePEDDf3SkW.jpg"},{name:"Samvedna Suwalka",character:"",photo:"/rWjPUFehWY5NFiEnrI1ZzpVDVmN.jpg"}]},
  {tmdbId:1284465,cast:[{name:"Hugh Jackman",character:"Robin Hood",photo:"/4Xujtewxqt6aU0Y81tsS9gkjizk.jpg"},{name:"Jodie Comer",character:"Sister Brigid",photo:"/AfsBpnfw0E2h8NZK4zkFcOjYlEb.jpg"},{name:"Bill Skarsgard",character:"Little John",photo:"/xBXLx1m0uzhXIbY3wN8lmPGeUHl.jpg"},{name:"Murray Bartlett",character:"The Leper",photo:"/eN20zfcRB2F51bmUbTK9byQCpb9.jpg"},{name:"Noah Jupe",character:"Arthur / Godwyn",photo:"/cBhJisZrIsZzamiUCVjOZODcqOK.jpg"},{name:"Jodie Comer",character:"Sister Brigid",photo:"/AfsBpnfw0E2h8NZK4zkFcOjYlEb.jpg"}]},
  {tmdbId:1657464,cast:[{name:"Raj Kundra",character:"",photo:null},{name:"Payal Rajput",character:"",photo:"/Dy77qpDnYSqQNPQ0x4Y7ZRDJrw.jpg"},{name:"Mahabir Bhullar",character:"",photo:"/oLqAyaImBLOIRY4cZLgRCrDmOee.jpg"},{name:"Amit Behl",character:"",photo:"/ioHVsBxl4xzw1N4nSWtKvtQiI0T.jpg"},{name:"Ankit Sagar",character:"",photo:"/bO5OWuAhZRaYohtZnWWOMQDkEWI.jpg"}]},
  {tmdbId:1443961,cast:[{name:"Satyadev Kancharana",character:"Rao Bahadur",photo:"/uIf1HM99iDVf9vdJwXPMgggOHkA.jpg"},{name:"Vikas Muppala",character:"Dr. Narayanachari",photo:null},{name:"Deepa Thomas",character:"Renuka",photo:"/XaAMnfjvpFfB1uhIXsRWqYGGsB.jpg"},{name:"Pranay Vaka",character:"Lavanappa",photo:"/e57mfqfT9Zos8BogFzkY2T4viHO.jpg"},{name:"Anand",character:"Jagannadhan",photo:"/nITOqirdTcd3hDCZvp8QWknV6WU.jpg"}]}
];

async function run() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  const movieSchema = new mongoose.Schema({
    tmdbId: Number, cast: mongoose.Schema.Types.Mixed, lastSyncedAt: Date
  }, { timestamps: true, strict: false });
  const Movie = mongoose.models.Movie || mongoose.model('Movie', movieSchema, 'movies');

  let updated = 0;
  for (const item of castData) {
    const result = await Movie.updateOne(
      { tmdbId: item.tmdbId },
      { $set: { cast: item.cast, lastSyncedAt: new Date() } }
    );
    if (result.modifiedCount > 0) updated++;
    console.log(item.tmdbId, 'cast updated, members:', item.cast.length);
  }
  console.log('Total updated:', updated);
  await mongoose.disconnect();
}

run().catch(function(e) { console.error(e); process.exit(1); });
